### PR TITLE
Use feed gem

### PR DESCRIPTION
**Pull request by jamierocks**

### CODE REVIEW

**Comment by Zarthus** [comment]
Based on https://github.com/jekyll/jekyll-feed it seems like you're missing the instruction of adding it to the gemfile. And we might want to use some of it's configuration methods?

Does this work? Did you test it? What does it improve over our current method? Will gh-pages support it?

**Comment by jamierocks** [comment]
Yeah it works, use it for my site :)

**Comment by jamierocks** [comment]
You can find a list of all the gems you can use with GH and their versions https://pages.github.com/versions/

**Comment by bendem** [comment]
https://github.com/korobi/weblog/commit/88296afdbcf2b02478dee4cbe1785da4ab431065

**Pull request closed without merging**
